# each population has different config (can be used for multi-population training)
name: "population2" # population name (used for logging and identification)
carrying_capacity: 23 # initial and max population size
speciation: # speciation division config
  target_species: 10 # target number of species in any given generation (can't be larger than population size)
  threshold_step: 0.7 # reduction step towards target number of species
  excess_factor: 1.0 # how much the excess genes affect compatibility
  disjoint_factor: 1.0 # how much the disjoint genes affect compatibility
  weight_factor: 1.0 # how much the sum of differences in connections affect compatibility
organism:
  inputs: 3 # number of sensors (inputs for nn)
  outputs: 2 # number of outputs for nn
  mutation_chance: 0.2 # chance for mutation to occur
  structural_mutation_chance: 0.6 # given mutation -> chance that structural mutation occurs given
  structural_connection_mutation_chance: 0.70 # given structural mutation -> chance that connection is added, otherwise add node
  structural_connection_addition_chance: 0.8 # given structural connection mutation -> chance that a connection is added instead of removed
  structural_node_addition_chance: 0.4 # given structural node mutation -> chance that a node is added instead of removed
  activation_function_mutation_chance: 0.4 # given regular mutation -> chance to update a nodes activation function
